=== GitHubProgrammerShui/eMarket/eMarket_resource/WebContent/resource/conf/PropertiesReader.dtd
<!ELEMENT properties (property*)>
<!ELEMENT property (string|list|map)>
<!ELEMENT string (#PCDATA)>
<!ELEMENT list (string*)>
<!ELEMENT map (entry*)>
<!ELEMENT entry (#PCDATA)>

<!ATTLIST property
	key CDATA #REQUIRED
>
<!ATTLIST entry
	key CDATA #REQUIRED
>

=== GitHubProgrammerShui/eMarket/eMarket_web/src/main/resources/application.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE properties SYSTEM "http://127.0.0.1:8092/resource/conf/PropertiesReader.dtd">
<properties>
	<!-- 这个配置文件记录了系统的相关配置信息，它们直接关系到一些功能的实现，请勿随意更改 -->
	<property key="customerImageUploadProfile">
		<map>
			<!-- 文件服务器地址 -->
			<entry key="ftpHostAddress">127.0.0.1</entry>
			<!-- 文件服务器登录用户名 -->
			<entry key="username">admin</entry>
			<!-- 文件服务器登录密码 -->
			<entry key="password">admin123</entry>
			<!-- 上传的商品图片位于文件服务器上的哪个目录，以"/"开始，表示从根目录开始 -->
			<entry key="uploadPath">/customer</entry>
		</map>
	</property>
	<property key="imgRootUrl">
		<string>http://127.0.0.1:8092/resource</string>
	</property>
</properties>

=== GitHubProgrammerShui/eMarket/eMarket_admin/src/main/resources/application.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE properties SYSTEM "http://127.0.0.1:8092/resource/conf/PropertiesReader.dtd">
<properties>
	<!-- 这个配置文件记录了系统的相关配置信息，它们直接关系到一些功能的实现，请勿随意更改 -->
	<!-- 配置商品图片文件上传的相关参数 -->
	<property key="goodsImageUploadProfile">
		<map>
			<!-- 文件服务器地址 -->
			<entry key="ftpHostAddress">127.0.0.1</entry>
			<!-- 文件服务器登录用户名 -->
			<entry key="username">admin</entry>
			<!-- 文件服务器登录密码 -->
			<entry key="password">admin123</entry>
			<!-- 上传的商品图片位于文件服务器上的哪个目录，以"/"开始，表示从根目录开始 -->
			<entry key="uploadPath">/goods</entry>
		</map>
	</property>
	<property key="workerImageUploadProfile">
		<map>
			<!-- 文件服务器地址 -->
			<entry key="ftpHostAddress">127.0.0.1</entry>
			<!-- 文件服务器登录用户名 -->
			<entry key="username">admin</entry>
			<!-- 文件服务器登录密码 -->
			<entry key="password">admin123</entry>
			<!-- 上传的商品图片位于文件服务器上的哪个目录，以"/"开始，表示从根目录开始 -->
			<entry key="uploadPath">/worker</entry>
		</map>
	</property>
	<property key="imgRootUrl">
		<string>http://127.0.0.1:8092/resource</string>
	</property>
	<!-- 配置可以直接访问的页面 ，目录与目录之间用“-”隔开 -->
	<property key="viewCollection">
		<list>
			<string>items-goods-list</string>
			<string>items-goods-saveorupdate</string>
			<string>items-goods-success</string>
			<string>items-order-list</string>
			<string>items-order-saveorupdate</string>
			<string>items-type-saveorupdate</string>
			<string>items-type-success</string>
			<string>items-worker-add</string>
			<string>items-factory-save</string>
			<string>items-brand-save</string>
		</list>
	</property>
</properties>
